###
POST http://localhost:8781/patients/create
Content-Type: application/json

{
  "name": "abhilash",
  "email": "someone@gmail.com",
  "address": "123, Kafka Town",
  "dateOfBirth": "2005-01-09",
  "registeredDate": "2025-04-03"
}


###
